"""Deterministic dedicated NGINX Gateway renderer and manifest validation."""
from __future__ import annotations
import hashlib, json, re
from dataclasses import dataclass, asdict
from gateway.errors import ValidationError, StateError
from gateway.models import StatePair, Strategy
from gateway.nginx_paths import NginxPaths, SERVICE_NAME
from gateway.runtime_apply import select_desired
from gateway.secrets import SecretStore

MAX_NGINX_MANIFEST_BYTES=512*1024
_TOKEN=re.compile(r"^[A-Za-z0-9._~-]+$")

def _q(value:str)->str:
    if not value or any(c in value for c in "{};\n\r\t\\\""):
        raise ValidationError("NGINX token contains unsafe characters")
    return value

def sha256(data:bytes)->str: return hashlib.sha256(data).hexdigest()

@dataclass(frozen=True)
class NginxUpstream:
    exit_id:str; address:str; port:int; backup:bool=False
@dataclass(frozen=True)
class NginxRoute:
    route_id:str; host:str; path:str; strategy:str; upstreams:tuple[NginxUpstream,...]
@dataclass(frozen=True)
class DesiredNginxGateway:
    enabled:bool; listen_address:str; listen_port:int; status_port:int; server_names:tuple[str,...]; routes:tuple[NginxRoute,...]
@dataclass(frozen=True)
class NginxManifest:
    service_name:str; nginx_bin:str; config_path:str; config_sha256:str; desired_enabled:bool; shared_revision:int; node_revision:int; route_count:int; backend_count:int

def select_desired_nginx(pair:StatePair, secrets:SecretStore)->DesiredNginxGateway:
    desired_exits={d.exit_id:d for d in select_desired(pair,secrets)}
    routes=[]
    for route in sorted(pair.shared.routes, key=lambda r:(r.host,r.path,r.id)):
        if not route.enabled: continue
        ups=[]
        usable=[eid for eid in route.exit_ids if eid in desired_exits]
        if not usable: raise ValidationError(f"enabled route {route.id} has no ready backend")
        for idx,eid in enumerate(usable):
            d=desired_exits[eid]
            ups.append(NginxUpstream(eid,"127.0.0.1",d.listen_port, route.strategy is Strategy.ACTIVE_PASSIVE and idx>0))
        routes.append(NginxRoute(route.id, route.host, route.path, route.strategy.value, tuple(ups)))
    return DesiredNginxGateway(pair.shared.gateway.enabled, pair.shared.gateway.listen_address, pair.shared.gateway.listen_port, pair.shared.gateway.status_port, tuple(sorted(pair.shared.gateway.server_names)), tuple(routes))

def render_config(desired:DesiredNginxGateway, paths:NginxPaths)->bytes:
    lines=["# Generated by GOST Manager. Do not edit.", "worker_processes auto;", "worker_rlimit_nofile 200000;", f"pid {paths.pid_file};", f"error_log {paths.error_log} warn;", "events {", "    worker_connections 16384;", "}", "http {", "    access_log off;", "    server_tokens off;", "    map $http_upgrade $connection_upgrade {", "        default upgrade;", "        '' close;", "    }"]
    for r in desired.routes:
        uname=f"{_q(r.route_id).replace('-','_')}"
        lines += [f"    upstream {uname} {{"]
        for u in r.upstreams:
            backup=" backup" if u.backup else ""
            lines.append(f"        server {_q(u.address)}:{u.port} max_fails=1 fail_timeout=2s{backup};")
        lines.append("    }")
    lines += ["    server {", "        listen 127.0.0.1:%d;"%desired.status_port, "        server_name _;", "        location = /nginx_status { stub_status; access_log off; allow 127.0.0.1; deny all; }", "        location / { return 404; }", "    }", "    server {", f"        listen {_q(desired.listen_address)}:{desired.listen_port};", "        server_name _;", "        return 444;", "    }"]
    for host in desired.server_names:
        host_routes=[r for r in desired.routes if r.host==host]
        lines += ["    server {", f"        listen {_q(desired.listen_address)}:{desired.listen_port};", f"        server_name {_q(host)};", "        location / { return 404; }"]
        for r in host_routes:
            uname=f"{_q(r.route_id).replace('-','_')}"
            lines += [f"        location = {_q(r.path)} {{", "            proxy_http_version 1.1;", "            proxy_set_header Upgrade $http_upgrade;", "            proxy_set_header Connection $connection_upgrade;", "            proxy_set_header Host $host;", "            proxy_set_header X-Real-IP $remote_addr;", "            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;", "            proxy_pass http://%s$request_uri;"%uname, "        }"]
        lines.append("    }")
    lines.append("}")
    data=("\n".join(lines)+"\n").encode()
    validate_config_bytes(data)
    return data

def validate_config_bytes(data:bytes)->None:
    text=data.decode('utf-8')
    if '/etc/nginx' in text or 'ssl_certificate' in text or 'quic' in text or 'http3' in text:
        raise ValidationError('NGINX config contains out-of-scope or unmanaged paths')
    if 'proxy_pass http://' not in text and 'return 444' not in text:
        raise ValidationError('NGINX config is incomplete')

def render_unit(paths:NginxPaths)->bytes:
    txt=f"""[Unit]\nDescription=GOST Manager dedicated NGINX Gateway\nAfter=network.target\nStartLimitIntervalSec=60\nStartLimitBurst=5\n\n[Service]\nType=forking\nPIDFile={paths.pid_file}\nExecStartPre={paths.nginx_bin} -t -c {paths.config_file} -p {paths.generated_dir}\nExecStart={paths.nginx_bin} -c {paths.config_file} -p {paths.generated_dir}\nExecReload={paths.nginx_bin} -t -c {paths.config_file} -p {paths.generated_dir}\nExecReload=/bin/kill -HUP $MAINPID\nExecStop=/bin/kill -QUIT $MAINPID\nRestart=on-failure\nRestartSec=3\nTimeoutStopSec=30\nKillMode=mixed\nLimitNOFILE=200000\nNoNewPrivileges=true\nPrivateTmp=true\nProtectHome=true\nProtectSystem=full\n\n[Install]\nWantedBy=multi-user.target\n"""
    return txt.encode()

def render_manifest(m:NginxManifest)->bytes:
    return (json.dumps(asdict(m), sort_keys=True, separators=(",",":"))+"\n").encode()

def parse_manifest(data:bytes)->NginxManifest:
    if len(data)>MAX_NGINX_MANIFEST_BYTES: raise StateError('NGINX manifest exceeds size limit')
    obj=json.loads(data.decode())
    exp=set(NginxManifest.__annotations__)
    if set(obj)!=exp: raise StateError('NGINX manifest contains missing or unknown fields')
    return NginxManifest(**obj)
