"""GOST Manager Upstream Watchdog v1."""

from gost_watchdog.models import (
    CHECK_INTERVAL_SECONDS,
    FAILURE_THRESHOLD,
    PING_TIMEOUT_SECONDS,
    RECOVERY_HOLD_SECONDS,
    RECOVERY_JITTER_MAX_SECONDS,
    SUCCESS_THRESHOLD,
)

__all__ = [
    "CHECK_INTERVAL_SECONDS",
    "FAILURE_THRESHOLD",
    "PING_TIMEOUT_SECONDS",
    "RECOVERY_HOLD_SECONDS",
    "RECOVERY_JITTER_MAX_SECONDS",
    "SUCCESS_THRESHOLD",
]
